//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SolicitudyAprobacion
    {
        public int Id { get; set; }
        public int IdCliente { get; set; }
        public System.DateTime FechaIngresoEmpresa { get; set; }
        public int SalarioMensual { get; set; }
        public string NombreEmpresa { get; set; }
        public string NitEmpresa { get; set; }
        public bool CreditoAprobado { get; set; }
    
        public virtual SolicitudyAprobacion SolicitudyAprobacion1 { get; set; }
        public virtual SolicitudyAprobacion SolicitudyAprobacion2 { get; set; }
    }
}
